### ISSUE TITLE
Secure Webservice

### ISSUE THREAD

**Issue by Systm21** [Chapoly1305/FindMy#3]
Hey, 
is it possible, to add some kind of user:password stageto the webif? It pains me to just have that on the internet.

**Comment by Chapoly1305** [comment]
> Hey, is it possible, to add some kind of user:password stageto the webif? It pains me to just have that on the internet.

Sorry for the late response. Yes, it is certainly possible. I recommend to setup a nginx service, you may refer to the https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/ for the configuration. 

The simplified setup would be, 
User - HTTP Auth/TLS -Nginx Service - FindMyService

It's usually easier to use nginx then edit the project for implementing classic http service auth and tls.

**Comment by Systm21** [comment]
The problem has already been solved, dchristl has already implemented a solution in his Macless haystack. There is no MQTT solution there, but this one doesn't work satisfactorily either. It's a mystery to me how these many people who use the project according to you don't realize this.

**Comment by Chapoly1305** [comment]
> The problem has already been solved, dchristl has already implemented a solution in his Macless haystack. There is no MQTT solution there, but this one doesn't work satisfactorily either. It's a mystery to me how these many people who use the project according to you don't realize this.

This is a "service", meant to run in a trusted environment. What you asked is a gateway. 
Commercial product do authentication and authorization on gateway, not on specific service unless have to. I am not seeing this project has an major issue without having embedded auth.
