### ISSUE TITLE
[Owntracks] combine "confidence" with "acc"

### ISSUE THREAD

**Issue by Systm21** [Chapoly1305/FindMy#6]
Hey, 
can you please combine the "confidence" data from apple with the "acc" var from owtracks json?

**Comment by Chapoly1305** [comment]
Sorry, I think there are people already using this project, so I won't edit this project directly otherwise may interfere other people's pipeline. If you can create a personal folk, I could help to provide a merge request for you.

**Comment by Systm21** [comment]
In what way should this be a problem? You actually make it even better by including the accuracy. The whole thing is already included in the data, it just has to be embedded in the json string that goes to the MQTT server.

**Comment by Chapoly1305** [comment]
> In what way should this be a problem? You actually make it even better by including the accuracy. The whole thing is already included in the data, it just has to be embedded in the json string that goes to the MQTT server.

I just realized I have thought about this when creating the MQTT JSON, the reason the ACC is not included is the confidence is not the "location in meters". So before figuring out how to calculate the "confidence" to "acc", or figure out a way to est. the acc, it might not appropriate to use this key. 

In my experience, the confidence increases when the device is closer to the tag, but it's not percentage, the value of confidence will be over 100. 

Ref
https://owntracks.org/booklet/tech/json/#:~:text=acc%20Accuracy%20of%20the%20reported%20location%20in%20meters%20without%20unit%20(iOS%2CAndroid/integer/meters/optional)
