### ISSUE TITLE
[Owntracks] Mqtt stops working. 

### ISSUE THREAD

**Issue by Systm21** [Chapoly1305/FindMy#8]
When i add a key to observe and make a crontab with curl to trigger a refresh, it dont gets updated. Only once, the first time when i add it.

**Comment by Chapoly1305** [comment]
> When i add a key to observe and make a crontab with curl to trigger a refresh, it dont gets updated. Only once, the first time when i add it.

This sounds like the execution of the crontab and irrelevant to this project directly. You may post the crontab record here, I could help to have a look.

**Comment by shiprec** [comment]
There is an in depth conversation going on here if you would like to join in:
https://github.com/biemster/FindMy/issues/40

**Comment by Systm21** [comment]
> There is an in depth conversation going on here if you would like to join in:

This have nothing to do with it, please stop spaming in every Topic. 



> This sounds like the execution of the crontab and irrelevant to this project directly. You may post the crontab record here, I could help to have a look.

I wouldn't post the problem here if it wasn't obviously related. If I trigger the whole thing directly via curl it works just as little. A problem can be excluded insofar as it generally works the first time, i.e. the first time it is published to the mqtt server. All subsequent attempts are confirmed as 200, but do not reach the MQTT server.

**Comment by Chapoly1305** [comment]
Insufficient information provided, no log, no execution steps, unable to determine to issue.

**Comment by Chapoly1305** [comment]
For the record, just checked, everything looks normal to me, mqtt posting is working as expected. I have no idea what's the issue about. The location of my tag updated right before I leave the house, and the earliest record was three days ago when I deployed for validating this issue. 

![image](https://github.com/Chapoly1305/FindMy/assets/25316415/9c99ab1e-5fe2-4032-b0a5-8639be127d1e)

**Comment by Chapoly1305** [comment]
I think this is related to this fix, https://github.com/Chapoly1305/FindMy/commit/cf64c3965b80c4d6ac39a8167cd0036182637f7a
